'use strict';
let options = {};
if(process.env.NODE_ENV === 'production'){
  options.schema = process.env.SCHEMA
}
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    options.tableName = 'Events';
    return queryInterface.bulkInsert(options, [
      {
        venueId: 1,
        groupId: 1,
        name: 'Event 1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'Online',
        capacity: 100,
        price: 9.99,
        startDate: new Date('2024-05-20T10:00:00Z'),
        endDate: new Date('2024-05-20T12:00:00Z'),
      },
      {
        venueId: 1,
        groupId: 2,
        name: 'Event 2',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 3,
        name: 'Event 3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 4,
        name: 'Event 4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 5,
        name: 'Event 5',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 6,
        name: 'Event 6',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 7,
        name: 'Event 7',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 8,
        name: 'Event 8',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 9,
        name: 'Event 9',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 10,
        name: 'Event 10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 1,
        name: 'Event 11',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'Online',
        capacity: 100,
        price: 9.99,
        startDate: new Date('2024-05-20T10:00:00Z'),
        endDate: new Date('2024-05-20T12:00:00Z'),
      },
      {
        venueId: 1,
        groupId: 2,
        name: 'Event 12',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 3,
        name: 'Event 13',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 4,
        name: 'Event 14',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 5,
        name: 'Event 15',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 6,
        name: 'Event 16',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 7,
        name: 'Event 17',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 8,
        name: 'Event 18',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 9,
        name: 'Event 19',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 10,
        name: 'Event 20',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 1,
        name: 'Event 21',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'Online',
        capacity: 100,
        price: 9.99,
        startDate: new Date('2024-05-20T10:00:00Z'),
        endDate: new Date('2024-05-20T12:00:00Z'),
      },
      {
        venueId: 1,
        groupId: 2,
        name: 'Event 22',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 3,
        name: 'Event 23',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 4,
        name: 'Event 24',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 5,
        name: 'Event 25',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 6,
        name: 'Event 26',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 7,
        name: 'Event 27',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 8,
        name: 'Event 28',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 9,
        name: 'Event 29',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      },{
        venueId: 1,
        groupId: 10,
        name: 'Event 30',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper auctor aliquam. Vivamus eleifend, erat sed cursus fringilla, arcu mauris pulvinar turpis, sit amet lacinia arcu lorem a ipsum.',
        type: 'In person',
        capacity: 50,
        price: 19.99,
        startDate: new Date('2024-05-22T14:00:00Z'),
        endDate: new Date('2024-05-22T16:00:00Z'),
      }
  ])},

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    options.tableName = 'Events';
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options, {
      type: { [Op.in]: ['Online','In person'] }
    }, {});
  }
};
